### PR TITLE
Fix head disappearing when dying at end of hole

### LINKED ISSUE #259: Head disappears mysteriously when Kurve crashes
As of #258 (1de43be4533262ae68c33ddfdd9d12f843c01bc8), make these changes:

```diff
--- a/src/Game.elm
+++ b/src/Game.elm
@@ -407,2 +407,2 @@ recordUserInteraction pressedButtons nextTick kurve =
     in
-    modifyReversedInteractions ((::) (HappenedBefore nextTick newTurningState)) kurve
+    kurve
--- a/src/Spawn.elm
+++ b/src/Spawn.elm
@@ -15,3 +15,3 @@ import Types.Angle exposing (Angle(..))
 import Types.Distance as Distance exposing (Distance)
-import Types.Kurve as Kurve exposing (Kurve)
+import Types.Kurve as Kurve exposing (Kurve, UserInteraction(..))
 import Types.Player exposing (Player)
@@ -19,2 +19,4 @@ import Types.PlayerId exposing (PlayerId)
 import Types.Radius as Radius
+import Types.Tick as Tick
+import Types.TurningState exposing (TurningState(..))
 import Util exposing (curry)
@@ -91,3 +93,7 @@ generateKurve config id numberOfPlayers existingPositions player =
             , stateAtSpawn = state
-            , reversedInteractions = []
+            , reversedInteractions =
+                [ HappenedBefore (202 |> Tick.fromInt |> Maybe.withDefault Tick.genesis) NotTurning
+                , HappenedBefore (71 |> Tick.fromInt |> Maybe.withDefault Tick.genesis) TurningLeft
+                , HappenedBefore (1 |> Tick.fromInt |> Maybe.withDefault Tick.genesis) NotTurning
+                ]
             }
```

> [!IMPORTANT]
> Patch must have trailing newline; otherwise `git apply` fails with `error: corrupt patch at line 27`.

Then join with Green and start the game as usual.

The round ends like this:

Image

**What happened to Green's head? Why did it disappear when Green crashed into itself?**

## System information

  * Windows 11
  * Firefox 146.0.1 and Chrome 143.0.7499.147

### PR DESCRIPTION
**Pull request by SimonAlling**
If a Kurve dies just as it closes a hole and becomes unholy (solid) again, its head disappears and it's not possible to tell where the Kurve died. As [documented] in #259, the bug has been present since the introduction of holes in 855ab5743769f7a91668f4c7e23c2f4c487a6502.

The bug can be visualized like this as of this PR (minus the changes in the `Game` module, which fix the bug):

```elm
init : () -> ( Model, Cmd Msg )
init _ =
    let
        model : Model
        model =
            { pressedButtons = Set.empty
            , appState = InMenu SplashScreen (Random.initialSeed 1337)
            , config = TestScenarios.CrashingWhileBecomingUnholy.config
            , players = initialPlayers
            }
    in
    startRound Replay
        model
        (prepareReplayRound
            { seedAfterSpawn = Random.initialSeed 0
            , spawnedKurves = TestScenarios.CrashingWhileBecomingUnholy.spawnedKurves
            }
        )
        |> Tuple.mapSecond makeCmd
```

Note that the config is `TestScenarios.CrashingWhileBecomingUnholy.config`, not `Config.default`!

The round should end like this:

⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛
⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛
⬛⬛⬛⬛🟩🟩🟩🟩🟩⬛⬛⬛⬛⬛🟩🟩🟩
⬛⬛⬛⬛🟩🟩🟩🟩🟩⬛⬛⬛⬛⬛🟩🟩🟩
⬛⬛⬛⬛🟩🟩🟩🟩🟩⬛⬛⬛⬛⬛🟩🟩🟩
⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛
⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛

But it ends like this:

⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛
⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛
⬛⬛⬛⬛🟩🟩🟩🟩🟩⬛⬛⬛⬛⬛⬛⬛⬛
⬛⬛⬛⬛🟩🟩🟩🟩🟩⬛⬛⬛⬛⬛⬛⬛⬛
⬛⬛⬛⬛🟩🟩🟩🟩🟩⬛⬛⬛⬛⬛⬛⬛⬛
⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛
⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛

This PR fixes the problem by letting `evaluateMove` know the Kurve's holiness at the _previous_ tick too, and using that information to make sure that the last position that a dying Kurve could be at is always drawn exactly once.

Resolves #259.

[documented]: https://github.com/SimonAlling/kurve/issues/259#issuecomment-3693453169

💡 `git show --color-words='-- .+|case oldHoliness of|holiness|.'`

### CODE REVIEW

File: src/Game.elm [hunk 1]
```diff
@@ -284,33 +284,43 @@ evaluateMove config startingPoint desiredEndPoint occupiedPixels holiness =
...
+                    checkedPositionsReversed
+
+                ( Lives, Holy, Holy ) ->
+                    []
+
+                ( Dies, Unholy, Unholy ) ->
+                    checkedPositionsReversed
+
+                ( Dies, Unholy, Holy ) ->
+                    List.head checkedPositionsReversed |> Maybe.map List.singleton |> Maybe.withDefault []
```
Comment (lydell) [inline src/Game.elm]:
```suggestion
                    List.take 1 checkedPositionsReversed
```

**Comment by SimonAlling** [comment]
Maybe comments need to be added and/or tweaked, and of course a description is needed, but WDYT about the fix itself, @lydell?

**Comment by SimonAlling** [comment]
I changed the structure slightly because I kept being confused about which one was the new and which was the old holiness when they were elements of a triple. No ordering seemed like the obviously natural one.
